/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBeanForm.java
 *
 * Created on Apr 20, 2012, 7:44:24 PM
 */
package com.components.custom;

import javax.swing.JTextField;

/**
 *
 * @author nnjj
 */
public class NewBeanForm extends JTextField {

    /** Creates new form NewBeanForm */
    public NewBeanForm() {
        initComponents();
    init();
    }

    public void init(){
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
