/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PInternalFrame.java
 *
 * Created on Oct 7, 2010, 1:40:11 PM
 */

package org.components.parent.containers;

import javax.swing.JInternalFrame;

/**
 *
 * @author nano
 */
public class PInternalFrame extends JInternalFrame {

    /** Creates new form BeanForm */
    public PInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
