/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * orgbutton.java
 *
 * Created on May 11, 2010, 9:51:09 PM
 */

package org.components.parent.controls;

import javax.swing.JButton;

/**
 *
 * @author nano
 */
public class PButton extends JButton {

    /** Creates new form BeanForm */
    public PButton() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setText("Button");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
