/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CCheckBox.java
 *
 * Created on Jan 5, 2011, 6:31:14 AM
 */

package org.components.parent.controls;

import javax.swing.JCheckBox;

/**
 *
 * @author mjawath
 */
public class PCheckBox extends JCheckBox {

    /** Creates new form BeanForm */
    public PCheckBox() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setText("Select");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
