/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PFrame.java
 *
 * Created on Oct 7, 2010, 1:22:18 PM
 */

package org.components.parent.windows;

import javax.swing.JFrame;

/**
 *
 * @author nano
 */
public class PFrame extends JFrame {

    /** Creates new form BeanForm */
    public PFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
