/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CCalender.java
 *
 * Created on Mar 8, 2011, 7:08:28 AM
 */

package org.components.controls;

/**
 *
 * @author mjawath
 */
public class CCalender extends  org.components.parent.controls.PCalender {

    /** Creates new form BeanForm */
    public CCalender() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
