/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CLabel.java
 *
 * Created on Dec 27, 2010, 10:34:55 PM
 */

package org.components.controls;

import org.components.parent.controls.PLabel;

/**
 *
 * @author mjawath
 */
public class CLabel extends PLabel {

    /** Creates new form BeanForm */
    public CLabel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(104, 25));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
