/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecievableForm.java
 *
 * Created on Jan 8, 2012, 6:28:28 PM
 */
package org.biz.invoicesystem.master.ui;

import javax.swing.JPanel;
import org.components.windows.TabPanelUI;

/**
 *
 * @author Administrator
 */
public class PayableForm  extends TabPanelUI {

    /** Creates new form RecievableForm */
    public PayableForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cLabel3 = new org.components.controls.CLabel();
        cComboBox1 = new org.components.controls.CComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        cTable1 = new org.components.controls.CTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cTable2 = new org.components.controls.CTable();
        cPanel1 = new org.components.containers.CPanel();
        cButton1 = new org.components.controls.CButton();
        cButton2 = new org.components.controls.CButton();
        cButton3 = new org.components.controls.CButton();
        cButton4 = new org.components.controls.CButton();
        cTextField1 = new org.components.controls.CTextField();
        cLabel1 = new org.components.controls.CLabel();
        cTextField3 = new org.components.controls.CTextField();
        cPanel2 = new org.components.containers.CPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cTable3 = new org.components.controls.CTable();
        cLabel4 = new org.components.controls.CLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cTextArea1 = new org.components.controls.CTextArea();
        cButton5 = new org.components.controls.CButton();
        cButton6 = new org.components.controls.CButton();
        cLabel8 = new org.components.controls.CLabel();
        cLabel2 = new org.components.controls.CLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(null);

        cLabel3.setText("Supplier");
        cLabel3.setFont(new java.awt.Font("Tahoma", 1, 10));
        add(cLabel3);
        cLabel3.setBounds(10, 10, 60, 20);

        cComboBox1.setEditable(true);
        add(cComboBox1);
        cComboBox1.setBounds(70, 10, 253, 23);

        cTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 226, 893, 150);

        cTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cus Id", "Company", "Debit", "Credit", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cTable2);
        cTable2.getColumnModel().getColumn(1).setMinWidth(200);
        cTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
        cTable2.getColumnModel().getColumn(1).setMaxWidth(200);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 65, 893, 150);

        cButton1.setText("<<");

        cButton2.setText("<");

        cButton3.setText(">>");

        cButton4.setText(">");

        javax.swing.GroupLayout cPanel1Layout = new javax.swing.GroupLayout(cPanel1);
        cPanel1.setLayout(cPanel1Layout);
        cPanel1Layout.setHorizontalGroup(
            cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanel1Layout.createSequentialGroup()
                .addComponent(cButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cPanel1Layout.setVerticalGroup(
            cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(cTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(cPanel1);
        cPanel1.setBounds(250, 40, 351, 25);

        cLabel1.setText("Remarks");
        add(cLabel1);
        cLabel1.setBounds(10, 400, 70, 25);
        add(cTextField3);
        cTextField3.setBounds(90, 480, 270, 25);

        cPanel2.setLayout(null);

        cTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(cTable3);

        cPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 490, 143);

        cLabel4.setText("Call All the Recieved Chqs");
        cPanel2.add(cLabel4);
        cLabel4.setBounds(10, 0, 480, 25);

        add(cPanel2);
        cPanel2.setBounds(390, 390, 510, 200);

        cTextArea1.setColumns(20);
        cTextArea1.setRows(5);
        jScrollPane4.setViewportView(cTextArea1);

        add(jScrollPane4);
        jScrollPane4.setBounds(90, 400, 270, 70);

        cButton5.setText("Save");
        add(cButton5);
        cButton5.setBounds(80, 570, 110, 30);

        cButton6.setText("Clear");
        add(cButton6);
        cButton6.setBounds(200, 570, 120, 30);

        cLabel8.setText("Cash");
        add(cLabel8);
        cLabel8.setBounds(10, 480, 70, 25);

        cLabel2.setText("Suplier Details");
        add(cLabel2);
        cLabel2.setBounds(340, 10, 310, 25);
        add(jSeparator1);
        jSeparator1.setBounds(580, 170, 50, 10);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.components.controls.CButton cButton1;
    private org.components.controls.CButton cButton2;
    private org.components.controls.CButton cButton3;
    private org.components.controls.CButton cButton4;
    private org.components.controls.CButton cButton5;
    private org.components.controls.CButton cButton6;
    private org.components.controls.CComboBox cComboBox1;
    private org.components.controls.CLabel cLabel1;
    private org.components.controls.CLabel cLabel2;
    private org.components.controls.CLabel cLabel3;
    private org.components.controls.CLabel cLabel4;
    private org.components.controls.CLabel cLabel8;
    private org.components.containers.CPanel cPanel1;
    private org.components.containers.CPanel cPanel2;
    private org.components.controls.CTable cTable1;
    private org.components.controls.CTable cTable2;
    private org.components.controls.CTable cTable3;
    private org.components.controls.CTextArea cTextArea1;
    private org.components.controls.CTextField cTextField1;
    private org.components.controls.CTextField cTextField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabName() {
       return "Recievable Form " ;
    }

    @Override
    public JPanel getJPanel() {
     return this;   }
}
