/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vehicle.java
 *
 * Created on Jan 12, 2012, 7:31:58 AM
 */
package org.biz.invoicesystem.master.ui;

/**
 *
 * @author Administrator
 */
public class Vehicle extends javax.swing.JPanel {

    /** Creates new form Vehicle */
    public Vehicle() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cButton1 = new org.components.controls.CButton();
        cLabel1 = new org.components.controls.CLabel();
        cComboBox1 = new org.components.controls.CComboBox();
        cTextField1 = new org.components.controls.CTextField();
        cLabel2 = new org.components.controls.CLabel();
        cTextField2 = new org.components.controls.CTextField();
        cLabel3 = new org.components.controls.CLabel();
        cTextField3 = new org.components.controls.CTextField();
        cLabel4 = new org.components.controls.CLabel();
        cTextField4 = new org.components.controls.CTextField();
        cLabel5 = new org.components.controls.CLabel();
        cLabel6 = new org.components.controls.CLabel();
        cDatePicker1 = new org.components.controls.CDatePicker();
        cLabel7 = new org.components.controls.CLabel();
        cDatePicker2 = new org.components.controls.CDatePicker();
        cLabel8 = new org.components.controls.CLabel();
        cComboBox2 = new org.components.controls.CComboBox();
        cButton2 = new org.components.controls.CButton();
        cButton3 = new org.components.controls.CButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTable1 = new org.components.parent.controls.PTable();

        setLayout(null);

        cButton1.setText("Delete");
        add(cButton1);
        cButton1.setBounds(350, 140, 80, 40);

        cLabel1.setText("Type");
        add(cLabel1);
        cLabel1.setBounds(10, 40, 70, 25);
        add(cComboBox1);
        cComboBox1.setBounds(100, 40, 170, 23);
        add(cTextField1);
        cTextField1.setBounds(100, 10, 170, 25);

        cLabel2.setText("Licence Expiry");
        add(cLabel2);
        cLabel2.setBounds(310, 50, 130, 20);
        add(cTextField2);
        cTextField2.setBounds(100, 70, 170, 25);

        cLabel3.setText("Year");
        add(cLabel3);
        cLabel3.setBounds(10, 70, 70, 25);
        add(cTextField3);
        cTextField3.setBounds(100, 100, 170, 25);

        cLabel4.setText("Chessie No");
        add(cLabel4);
        cLabel4.setBounds(10, 100, 80, 25);
        add(cTextField4);
        cTextField4.setBounds(400, 20, 170, 25);

        cLabel5.setText("Engine No");
        add(cLabel5);
        cLabel5.setBounds(310, 20, 80, 25);

        cLabel6.setText("Reg.No");
        add(cLabel6);
        cLabel6.setBounds(10, 10, 70, 25);
        add(cDatePicker1);
        cDatePicker1.setBounds(440, 50, 130, 20);

        cLabel7.setText("Insurance Expiry");
        add(cLabel7);
        cLabel7.setBounds(310, 80, 130, 20);
        add(cDatePicker2);
        cDatePicker2.setBounds(440, 80, 130, 20);

        cLabel8.setText("Ownership");
        add(cLabel8);
        cLabel8.setBounds(310, 110, 104, 20);

        cComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Own", "Lease", "Hired" }));
        add(cComboBox2);
        cComboBox2.setBounds(440, 110, 130, 20);

        cButton2.setText("Save");
        add(cButton2);
        cButton2.setBounds(150, 140, 80, 40);

        cButton3.setText("Clear/Refresh");
        add(cButton3);
        cButton3.setBounds(240, 140, 100, 40);

        pTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg No", "Type", "Owner Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 560, 190);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.components.controls.CButton cButton1;
    private org.components.controls.CButton cButton2;
    private org.components.controls.CButton cButton3;
    private org.components.controls.CComboBox cComboBox1;
    private org.components.controls.CComboBox cComboBox2;
    private org.components.controls.CDatePicker cDatePicker1;
    private org.components.controls.CDatePicker cDatePicker2;
    private org.components.controls.CLabel cLabel1;
    private org.components.controls.CLabel cLabel2;
    private org.components.controls.CLabel cLabel3;
    private org.components.controls.CLabel cLabel4;
    private org.components.controls.CLabel cLabel5;
    private org.components.controls.CLabel cLabel6;
    private org.components.controls.CLabel cLabel7;
    private org.components.controls.CLabel cLabel8;
    private org.components.controls.CTextField cTextField1;
    private org.components.controls.CTextField cTextField2;
    private org.components.controls.CTextField cTextField3;
    private org.components.controls.CTextField cTextField4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.components.parent.controls.PTable pTable1;
    // End of variables declaration//GEN-END:variables
}
