/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VehicleSaleForm.java
 *
 * Created on Jan 11, 2012, 5:30:07 PM
 */
package org.biz.invoicesystem.master.ui;

/**
 *
 * @author Administrator
 */
public class VehicleSaleForm extends javax.swing.JPanel {

    /** Creates new form VehicleSaleForm */
    public VehicleSaleForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cLabel1 = new org.components.controls.CLabel();
        cComboBox1 = new org.components.controls.CComboBox();
        cLabel2 = new org.components.controls.CLabel();
        cComboBox2 = new org.components.controls.CComboBox();
        cLabel3 = new org.components.controls.CLabel();
        cComboBox3 = new org.components.controls.CComboBox();
        cLabel4 = new org.components.controls.CLabel();
        cTextField1 = new org.components.controls.CTextField();
        cLabel5 = new org.components.controls.CLabel();
        cTextField2 = new org.components.controls.CTextField();
        cTextField3 = new org.components.controls.CTextField();
        cButton1 = new org.components.controls.CButton();
        cButton2 = new org.components.controls.CButton();
        cTextField4 = new org.components.controls.CTextField();
        cTextField5 = new org.components.controls.CTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cTable1 = new org.components.controls.CTable();
        pButton1 = new org.components.parent.controls.PButton();
        pButton2 = new org.components.parent.controls.PButton();
        pButton3 = new org.components.parent.controls.PButton();
        pButton4 = new org.components.parent.controls.PButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        cLabel1.setText("Sales Rep");
        add(cLabel1);
        cLabel1.setBounds(10, 10, 84, 25);

        cComboBox1.setEditable(true);
        add(cComboBox1);
        cComboBox1.setBounds(90, 10, 190, 23);

        cLabel2.setText("Vehicle");
        add(cLabel2);
        cLabel2.setBounds(10, 70, 84, 25);

        cComboBox2.setEditable(true);
        add(cComboBox2);
        cComboBox2.setBounds(90, 70, 190, 23);

        cLabel3.setText("Qty");
        add(cLabel3);
        cLabel3.setBounds(260, 120, 100, 25);

        cComboBox3.setEditable(true);
        add(cComboBox3);
        cComboBox3.setBounds(110, 150, 140, 23);

        cLabel4.setText("Item id");
        add(cLabel4);
        cLabel4.setBounds(110, 120, 120, 25);
        add(cTextField1);
        cTextField1.setBounds(260, 150, 90, 25);

        cLabel5.setText("S.Price");
        add(cLabel5);
        cLabel5.setBounds(360, 120, 100, 25);
        add(cTextField2);
        cTextField2.setBounds(400, 10, 140, 20);
        add(cTextField3);
        cTextField3.setBounds(360, 150, 90, 25);

        cButton1.setText("Print");
        add(cButton1);
        cButton1.setBounds(450, 60, 90, 30);

        cButton2.setText("Load");
        add(cButton2);
        cButton2.setBounds(450, 30, 90, 23);
        add(cTextField4);
        cTextField4.setBounds(260, 180, 90, 25);
        add(cTextField5);
        cTextField5.setBounds(360, 180, 90, 25);

        cTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 530, 260);

        pButton1.setText("Delete");
        add(pButton1);
        pButton1.setBounds(390, 490, 100, 30);

        pButton2.setText("Save");
        add(pButton2);
        pButton2.setBounds(60, 490, 100, 30);

        pButton3.setText("Clear");
        add(pButton3);
        pButton3.setBounds(280, 490, 100, 30);

        pButton4.setText("Confirm");
        pButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton4ActionPerformed(evt);
            }
        });
        add(pButton4);
        pButton4.setBounds(170, 490, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void pButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.components.controls.CButton cButton1;
    private org.components.controls.CButton cButton2;
    private org.components.controls.CComboBox cComboBox1;
    private org.components.controls.CComboBox cComboBox2;
    private org.components.controls.CComboBox cComboBox3;
    private org.components.controls.CLabel cLabel1;
    private org.components.controls.CLabel cLabel2;
    private org.components.controls.CLabel cLabel3;
    private org.components.controls.CLabel cLabel4;
    private org.components.controls.CLabel cLabel5;
    private org.components.controls.CTable cTable1;
    private org.components.controls.CTextField cTextField1;
    private org.components.controls.CTextField cTextField2;
    private org.components.controls.CTextField cTextField3;
    private org.components.controls.CTextField cTextField4;
    private org.components.controls.CTextField cTextField5;
    private javax.swing.JScrollPane jScrollPane1;
    private org.components.parent.controls.PButton pButton1;
    private org.components.parent.controls.PButton pButton2;
    private org.components.parent.controls.PButton pButton3;
    private org.components.parent.controls.PButton pButton4;
    // End of variables declaration//GEN-END:variables
}
