/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecievableForm.java
 *
 * Created on Jan 8, 2012, 6:28:28 PM
 */
package org.biz.invoicesystem.master.ui;

import javax.swing.JPanel;
import org.components.windows.TabPanelUI;

/**
 *
 * @author Administrator
 */
public class RecievableForm  extends TabPanelUI {

    /** Creates new form RecievableForm */
    public RecievableForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cLabel3 = new org.components.controls.CLabel();
        cComboBox1 = new org.components.controls.CComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        cTable1 = new org.components.controls.CTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cTable2 = new org.components.controls.CTable();
        cPanel1 = new org.components.containers.CPanel();
        cButton1 = new org.components.controls.CButton();
        cButton2 = new org.components.controls.CButton();
        cButton3 = new org.components.controls.CButton();
        cButton4 = new org.components.controls.CButton();
        cTextField1 = new org.components.controls.CTextField();
        cLabel1 = new org.components.controls.CLabel();
        cTextField3 = new org.components.controls.CTextField();
        cPanel2 = new org.components.containers.CPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cTable3 = new org.components.controls.CTable();
        cDatePicker1 = new org.components.controls.CDatePicker();
        cLabel4 = new org.components.controls.CLabel();
        cLabel5 = new org.components.controls.CLabel();
        cTextField4 = new org.components.controls.CTextField();
        cLabel6 = new org.components.controls.CLabel();
        cTextField5 = new org.components.controls.CTextField();
        cLabel7 = new org.components.controls.CLabel();
        cComboBox2 = new org.components.controls.CComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        cTextArea1 = new org.components.controls.CTextArea();
        cButton5 = new org.components.controls.CButton();
        cButton6 = new org.components.controls.CButton();
        cLabel8 = new org.components.controls.CLabel();
        cCheckBox1 = new org.components.controls.CCheckBox();
        cComboBox3 = new org.components.controls.CComboBox();
        cLabel2 = new org.components.controls.CLabel();

        setLayout(null);

        cLabel3.setText("Customer");
        cLabel3.setFont(new java.awt.Font("Tahoma", 1, 10));
        add(cLabel3);
        cLabel3.setBounds(10, 10, 60, 20);

        cComboBox1.setEditable(true);
        add(cComboBox1);
        cComboBox1.setBounds(70, 10, 253, 23);

        cTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 893, 156);

        cTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cus Id", "Company", "Debit", "Credit", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cTable2);
        cTable2.getColumnModel().getColumn(1).setMinWidth(200);
        cTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
        cTable2.getColumnModel().getColumn(1).setMaxWidth(200);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 65, 893, 150);

        cButton1.setText("<<");

        cButton2.setText("<");

        cButton3.setText(">>");

        cButton4.setText(">");

        javax.swing.GroupLayout cPanel1Layout = new javax.swing.GroupLayout(cPanel1);
        cPanel1.setLayout(cPanel1Layout);
        cPanel1Layout.setHorizontalGroup(
            cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanel1Layout.createSequentialGroup()
                .addComponent(cButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cPanel1Layout.setVerticalGroup(
            cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(cTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(cPanel1);
        cPanel1.setBounds(250, 40, 351, 25);

        cLabel1.setText("Remarks");
        add(cLabel1);
        cLabel1.setBounds(10, 400, 70, 25);
        add(cTextField3);
        cTextField3.setBounds(90, 480, 270, 25);

        cPanel2.setLayout(null);

        cTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(cTable3);

        cPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 490, 143);
        cPanel2.add(cDatePicker1);
        cDatePicker1.setBounds(10, 20, 83, 22);

        cLabel4.setText("CHQ Date");
        cPanel2.add(cLabel4);
        cLabel4.setBounds(10, 0, 73, 25);

        cLabel5.setText("CHQ Number");
        cPanel2.add(cLabel5);
        cLabel5.setBounds(100, 0, 112, 25);
        cPanel2.add(cTextField4);
        cTextField4.setBounds(100, 20, 134, 25);

        cLabel6.setText("OWN/PARTY");
        cPanel2.add(cLabel6);
        cLabel6.setBounds(390, 0, 112, 25);
        cPanel2.add(cTextField5);
        cTextField5.setBounds(240, 20, 134, 25);

        cLabel7.setText("CHQ Amount");
        cPanel2.add(cLabel7);
        cLabel7.setBounds(240, 0, 112, 25);
        cPanel2.add(cComboBox2);
        cComboBox2.setBounds(390, 20, 100, 23);

        add(cPanel2);
        cPanel2.setBounds(390, 390, 510, 210);

        cTextArea1.setColumns(20);
        cTextArea1.setRows(5);
        jScrollPane4.setViewportView(cTextArea1);

        add(jScrollPane4);
        jScrollPane4.setBounds(90, 400, 270, 70);

        cButton5.setText("Save");
        add(cButton5);
        cButton5.setBounds(80, 570, 110, 30);

        cButton6.setText("Clear");
        add(cButton6);
        cButton6.setBounds(200, 570, 120, 30);

        cLabel8.setText("Cash");
        add(cLabel8);
        cLabel8.setBounds(10, 480, 70, 25);

        cCheckBox1.setText("Cash To Bank");
        cCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(cCheckBox1);
        cCheckBox1.setBounds(10, 520, 110, 23);
        add(cComboBox3);
        cComboBox3.setBounds(160, 520, 200, 23);

        cLabel2.setText("Customer Details");
        add(cLabel2);
        cLabel2.setBounds(340, 10, 310, 25);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.components.controls.CButton cButton1;
    private org.components.controls.CButton cButton2;
    private org.components.controls.CButton cButton3;
    private org.components.controls.CButton cButton4;
    private org.components.controls.CButton cButton5;
    private org.components.controls.CButton cButton6;
    private org.components.controls.CCheckBox cCheckBox1;
    private org.components.controls.CComboBox cComboBox1;
    private org.components.controls.CComboBox cComboBox2;
    private org.components.controls.CComboBox cComboBox3;
    private org.components.controls.CDatePicker cDatePicker1;
    private org.components.controls.CLabel cLabel1;
    private org.components.controls.CLabel cLabel2;
    private org.components.controls.CLabel cLabel3;
    private org.components.controls.CLabel cLabel4;
    private org.components.controls.CLabel cLabel5;
    private org.components.controls.CLabel cLabel6;
    private org.components.controls.CLabel cLabel7;
    private org.components.controls.CLabel cLabel8;
    private org.components.containers.CPanel cPanel1;
    private org.components.containers.CPanel cPanel2;
    private org.components.controls.CTable cTable1;
    private org.components.controls.CTable cTable2;
    private org.components.controls.CTable cTable3;
    private org.components.controls.CTextArea cTextArea1;
    private org.components.controls.CTextField cTextField1;
    private org.components.controls.CTextField cTextField3;
    private org.components.controls.CTextField cTextField4;
    private org.components.controls.CTextField cTextField5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabName() {
       return "Recievable Form " ;
    }

    @Override
    public JPanel getJPanel() {
     return this;   }
}
