/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PDatePicker.java
 *
 * Created on Jun 28, 2010, 9:17:22 PM
 */

package org.components.parent.controls;

import org.jdesktop.swingx.JXMonthView;

/**
 *
 * @author nano
 */
public class PCalender extends JXMonthView {

    /** Creates new form BeanForm */
    public PCalender() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
