/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComboBox.java
 *
 * Created on May 6, 2010, 6:56:55 PM
 */

package org.components.parent.controls;

import org.components.controls.*;
import javax.swing.JComboBox;

/**
 *
 * @author nano
 */
public class PComboBox extends JComboBox {

    /** Creates new form BeanForm */
    public PComboBox() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
