/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CButton.java
 *
 * Created on May 11, 2010, 9:55:29 PM
 */

package org.components.controls;

import org.components.parent.controls.PButton;

/**
 *
 * @author nano
 */
public class CButton extends PButton {

    /** Creates new form BeanForm */
    public CButton() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
