/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cTabPane.java
 *
 * Created on Jan 11, 2012, 5:41:17 PM
 */
package org.components.controls;

import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 */
public class cTabPane extends JTabbedPane {

    /** Creates new form cTabPane */
    public cTabPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
